function fetch_helper_list() {
  return [
    {
      name: "Sussy Baka",
      base_cost: 15,
      cost: 15,
      base_sps: 0.1,
      sps: 0.1,
      description: "epic sussy baka super susssllyyy suslllyy",
      icon: "images/helpers/SussyBaka.png",
      quantity: 0,
      sound_path: "sound/helpers/SussyBaka/",
      sfx_quantity: 3,
      total_farmed: 0,
      verb: "impostered",
    },
    {
      name: "PewDiePie",
      base_cost: 100,
      cost: 100,
      base_sps: 1,
      sps: 1,
      description: "what a fucking- (dies)",
      icon: "images/helpers/PewDiePie.gif",
      quantity: 0,
      sound_path: "sound/helpers/PewDiePie/",
      sfx_quantity: 1,
      total_farmed: 0,
      verb: "slurred on bridges",
    },
    {
      name: "John Cena",
      base_cost: 1100,
      cost: 1100,
      base_sps: 8,
      sps: 8,
      description: "greetings, china. I have ice cream... YOU CAN'T SEE ME, MY TIME IS NOW111!!!",
      icon: "images/helpers/JohnCena.png",
      quantity: 0,
      sound_path: "sound/helpers/JohnCena/",
      sfx_quantity: 2,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "Mr.Incredible",
      base_cost: 12000,
      cost: 12000,
      base_sps: 47,
      sps: 47,
      description: "A once great man, some would even say incredible, who unfortunately sussied his way into the pits of absolute uncannyness",
      icon: "images/helpers/MisterIncredible/1.jpg",
      quantity: 0,
      sound_path: "sound/helpers/MisterIncredible/",
      sfx_quantity: 1,
      total_farmed: 0,
      verb: "uncannied",
    },
    {
      name: "Suspicious Son",
      base_cost: 130000,
      cost: 130000,
      base_sps: 260,
      sps: 260,
      description: "What's more sus than AC? AC and his son Boss AC",
      icon: "images/helpers/AntonioCosta.gif",
      quantity: 0,
      sound_path: "sound/helpers/FilhosACosta/",
      sfx_quantity: 1,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "Among Sus",
      base_cost: 1400000,
      cost: 1400000,
      base_sps: 1400,
      sps: 1400,
      description: "You can't see them but they're among sus...",
      icon: "images/helpers/AmongSus.gif",
      quantity: 0,
      sound_path: "sound/helpers/AmongSus/",
      sfx_quantity: 3,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "Turing Machine",
      base_cost: 20000000,
      cost: 20000000,
      base_sps: 7800,
      sps: 7800,
      description: "A mathematical model of computation developed by Supicious Turing III with the goal of sussyfying the world",
      icon: "images/helpers/TuringMachine.jpg",
      quantity: 0,
      sound_path: "sound/helpers/TuringMachine/",
      sfx_quantity: 1,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 2",
      base_cost: 330000000,
      cost: 330000000,
      base_sps: 44000,
      sps: 44000,
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 3",
      base_cost: 5.1 * Math.pow(10, 9),
      cost: 5.1 * Math.pow(10, 9),
      base_sps: 260000,
      sps: 260000,
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 4",
      base_cost: 75 * Math.pow(10, 9),
      cost: 75 * Math.pow(10, 9),
      base_sps: 1600000,
      sps: 1600000,
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 5",
      base_cost: 1 * Math.pow(10, 12),
      cost: 1 * Math.pow(10, 12),
      base_sps: 10000000,
      sps: 10000000,
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 6",
      base_cost: 14 * Math.pow(10, 12),
      cost: 14 * Math.pow(10, 12),
      base_sps: 65 * Math.pow(10, 6),
      sps: 65 * Math.pow(10, 6),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 7",
      base_cost: 170 * Math.pow(10, 12),
      cost: 170 * Math.pow(10, 12),
      base_sps: 430 * Math.pow(10, 6),
      sps: 430 * Math.pow(10, 6),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 8",
      base_cost: 2.1 * Math.pow(10, 15),
      cost: 2.1 * Math.pow(10, 15),
      base_sps: 2.9 * Math.pow(10, 9),
      sps: 2.9 * Math.pow(10, 9),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 9",
      base_cost: 26 * Math.pow(10, 15),
      cost: 26 * Math.pow(10, 15),
      base_sps: 21 * Math.pow(10, 9),
      sps: 21 * Math.pow(10, 9),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 10",
      base_cost: 310 * Math.pow(10, 15),
      cost: 310 * Math.pow(10, 15),
      base_sps: 150 * Math.pow(10, 9),
      sps: 150 * Math.pow(10, 9),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 11",
      base_cost: 71 * Math.pow(10, 18),
      cost: 71 * Math.pow(10, 18),
      base_sps: 1.1 * Math.pow(10, 12),
      sps: 1.1 * Math.pow(10, 12),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 12",
      base_cost: 12 * Math.pow(10, 21),
      cost: 12 * Math.pow(10, 21),
      base_sps: 8.3 * Math.pow(10, 12),
      sps: 8.3 * Math.pow(10, 12),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 13",
      base_cost: 1.9 * Math.pow(10, 24),
      cost: 1.9 * Math.pow(10, 24),
      base_sps: 64 * Math.pow(10, 12),
      sps: 64 * Math.pow(10, 12),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
    {
      name: "new building 14",
      base_cost: 1.9 * Math.pow(10, 24),
      cost: 1.9 * Math.pow(10, 24),
      base_sps: 64 * Math.pow(10, 12),
      sps: 64 * Math.pow(10, 12),
      description: "some new desc wtv",
      icon: "images/helpers/new.png",
      quantity: 0,
      sound_path: "sound/helpers/new/",
      sfx_quantity: 0,
      total_farmed: 0,
      verb: "define me please",
    },
  ];
} 
